// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqbcnsucudgxtslaohsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYmNuc3VjdWRneHRzbGFvaHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjI0MTksImV4cCI6MjA2OTg5ODQxOX0.A2daeNMU4hDRAojsGZlduU6wyiswDhVHTH4h1-kJSyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});